version: '3.8'

services:
  web:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    image: 'fiuni_hackazon_prod'
    container_name: pointofview_web_prod
    restart: always
    env_file:
      - '.env'
    expose:
      - "80"
      - "3306"
    volumes:
      - 'web_mysqldata_prod:/var/lib/mysql'
    networks:
      - pointofview_network_prod
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"

      - "traefik.http.routers.pointofview.rule=Host(`pointofview.rbnetto.dev`)"
      - "traefik.http.routers.pointofview.entrypoints=websecure"
      - "traefik.http.routers.pointofview.tls.certresolver=letsencrypt"

      - "traefik.http.services.pointofview.loadbalancer.server.port=80"
      - "traefik.http.services.pointofview.loadbalancer.server.scheme=http"

      - "traefik.http.routers.pointofview-redirect.rule=Host(`pointofview.rbnetto.dev`)"
      - "traefik.http.routers.pointofview-redirect.entrypoints=web"
      - "traefik.http.routers.pointofview-redirect.middlewares=pointofview-redirect-to-https"

      - "traefik.http.middlewares.pointofview-redirect-to-https.redirectscheme.scheme=https"

volumes:
  web_mysqldata_prod:

networks:
  pointofview_network_prod:
    name: pointofview_network_prod
  traefik_proxy:
    external: true
    name: traefik_proxy

